---
- name: Install zip if not available
  apt: name=zip update_cache=yes

- name: Install git if not available
  apt: name=git update_cache=yes

- name: Install mercurial if not available
  apt: name=mercurial update_cache=yes

- name: Download the Go tarball
  get_url: url=https://storage.googleapis.com/golang/go1.3.3.linux-amd64.tar.gz
           dest=/usr/local/src/go1.3.3.linux-amd64.tar.gz

- name: Extract the Go tarball
  command: tar -C /usr/local -xf /usr/local/src/go1.3.3.linux-amd64.tar.gz

- name: Add GOPATH
  copy:
    content: "export GOPATH=~"
    dest: /etc/profile.d/golang.sh

- name: Add Go to PATH
  copy:
    content: "export PATH=$PATH:/usr/local/go/bin:~/bin"
    dest: /etc/profile.d/golang.sh

- name: Install godep
  shell: /usr/local/go/bin/go get github.com/tools/godep
  environment:
    GOPATH: ~

